### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by holtwick** [paullouisageneau/violet#13]
This project is super awesome. I would like to offer it as a coturn alternative for people that like to install my Open Source tool https://github.com/holtwick/briefing/

Did you consider bundling it for Docker via https://hub.docker.com ? I think this would make it very attractive for regular users.

**Comment by paullouisageneau** [comment]
Thank you for your interest in the project. Your open source tool Briefing looks pretty nice!

FYI a Dockerfile has been added in https://github.com/paullouisageneau/violet/pull/14. I'll push an image to Docker Hub.

**Comment by holtwick** [comment]
Thanks. I'll try to get it to work with Briefing and give users introductions how to use it as a STUN/TURN server for it. Once it is working it will be such a nice lightweight setup :)

**Comment by paullouisageneau** [comment]
I pushed an image on Docker Hub: [paullouisageneau/violet](https://hub.docker.com/repository/docker/paullouisageneau/violet)

**Comment by holtwick** [comment]
@paullouisageneau finally I found the time to play around with the docker image.

It seems to work. I made some modifications, that might be useful for the project:

In `Dockerfile` I changed the last line to load a config file. Environment variables are not supported, right?

```
CMD [ "/usr/local/bin/violet", "--file=/etc/violet/violet.conf" ]
```

I then created a config file like this

```conf
# Log level
log-level=info

# Log file (default stdout)
log=/etc/violet/violet.log

# Port for STUN/TURN server
port=3478

# Port range for TURN relay
range=49152:49252

# Local address to bind (default any)
# bind=0.0.0.0

# External address to advertise for TURN relay (default automatic)
external=49.12.100.3

# TURN credentials with optional quota (default none)
credentials=brie:fi
quota=50 

# Global maximum number of allocations
#max=1024
```

Notice, I limited the relay ports.

The in a `docker-compose.yml` I used this:

```yaml
version: "3"

services:
  violet:
    container_name: violet
    # build: .
    image: paullouisageneau/violet
    restart: unless-stopped    
    ports:
    - "3478:3478"
    - "3478:3478/udp"
    - "49152-49252:49152-49252"
    - "49152-49252:49152-49252/udp"
    volumes:
    - ./data:/etc/violet
```

Commenting out `image:` and activating`build: .` would allow to do local builds like: `docker-compose build`.

I'm not sure about UDP or not. Probably this all could even become shorter. I took inspirations from here https://github.com/coturn/coturn/blob/master/docker/docker-compose-all.yml#L64
